### ISSUE TITLE
feature: 200-code health check endpoint

### ISSUE THREAD

**Issue by oyed** [colyseus/proxy#17]
When using this in Docker, it'd be useful to have a built-in `/health` route which just returned an empty 200 response, currently I'm making the health check URL `my.proxy.com/matchmaker` which forwards it to a Colyseus server for a 200, which poses a couple problems:

- It has to matchmake to be healthy
- If servers fail and none are available then the proxy would be considered unhealthy

**Comment by damnedOperator** [comment]
This is a requirement for anyone who wants to healthcheck via http (e.g in Kubernetes)

**Comment by endel** [comment]
Just merged https://github.com/colyseus/proxy/pull/35 addressing this 🙏
