### ISSUE TITLE
always get error when I run comand “npm start”

### ISSUE THREAD

**Issue by lyh1091106900** [colyseus/proxy#19]
system： Win10
node：14.15.4

I got error when I run comand “npm start” `PM2][ERROR] Error: Interpreter F:\proxy-master\pm2-example\node_modules\pm2\node_modules\.bin\ts-node is NOT AVAILABLE in PATH. (type 'which F:\proxy-master\pm2-example\node_modules\pm2\node_modules\.bin\ts-node' to double check.)`,I don,t know why locate to this dir,because ts-node is under  F:\proxy-master\pm2-example\node_modules/ts-node.
my ecosystem.config.js: 
 `module.exports = {
  apps : [
    {
      name      : 'colyseus-app',
      script    : 'index.ts',
      interpreter: "ts-node",
      watch     : false,
      instances : 3,
      exec_mode : 'fork',
      port      : 8080,
      env: {
        NODE_ENV: 'development',
        DEBUG: 'colyseus:errors,colyseus:matchmaking'
      },
    },
    {
      name: 'proxy',
      script: './node_modules/@colyseus/proxy/bin/proxy',
      instances: 1, // os.cpus().length,
      exec_mode: 'fork',
      env: {
        REDIS_URL: process.env.REDIS_URL,
      }
    }],
};
`

**Comment by endel** [comment]
Hi @lyh1091106900, I see that you had some progress here https://github.com/colyseus/proxy/issues/21

Do you still need help with this #19, and https://github.com/colyseus/proxy/issues/20, or can we close them?

**Comment by lyh1091106900** [comment]
I close the othre two issue,but that one still doesn't work

**Comment by lyh1091106900** [comment]
I think this issue  must be problem of pm2 and ts-node,but Ithink in the project, ts-node support should be remove because it a can easily occur.
